-- 특정 칼럼 혹은 값이 널 값인지 아닌지를 판단하는 연산자이다. IS NULL 혹은 IS NOT NULL로 널 유무를 판단한다.
create table t2 
(
	ID INT generated by default as identity,
	first_name varchar(50) not null,
	last_name varchar(50) not null,
	email varchar(255) not null,
	phone varchar(15),
	primary key (ID)
);
insert 
	into
	t2(first_name, last_name, email, phone)
	values
	('John', 'Doe', 'john.doe@example.com', null),
	('Lily', 'Bush', 'lily.bush@example.com', '(408-234-2764)');
commit;

-------------------------------------------------------------------
select 
	*
from 
	t2

-------------------------------------------------------------------
select
	*
from 
	t2
where
	-- phone = null -> null값은 = 연산을 사용하여 구할 수 없다.
	phone is null

-------------------------------------------------------------------
select
	*
from 
	t2
where
	phone is not null