-- DDL(DATA DEFINITION LANGUAGE)
DROP TABLE SQLD.TB_DEPT_TEMP PURGE; -- CREATE 전 초기화
CREATE TABLE SQLD.TB_DEPT_TEMP 
(
	DEPT_CD CHAR(6) NOT NULL,
	DEPT_NM VARCHAR2(150) NOT NULL,
	UPPER_DEPT_CD CHAR(6)
);

ALTER TABLE SQLD.TB_DEPT_TEMP ADD CONSTRAINT PK_TB_DEPT_TEMP PRIMARY KEY (DEPT_CD);

DROP TABLE SQLD.TB_DEPT_TEMP PURGE; -- PURGE를 뒤에 붙여주면 윈도우에서의 SHIFT + DELETE와 같이 백업파일을 남기지 않고 깔끔하게 삭제한다.

----------------------------------
DROP TABLE SQLD.TB_EMP_TEMP PURGE; -- CREATE 전 초기화
CREATE TABLE SQLD.TB_EMP_TEMP
(
	EMP_NO CHAR(10) NOT NULL,
	EMP_NM VARCHAR2(150) NOT NULL,
	BIRTH_DE CHAR(8) NOT NULL,
	LUNAR_YN CHAR(1) NOT NULL,
	SEX_CD CHAR(3) NOT NULL,
	ADDR VARCHAR2(1000) NOT NULL,
	TEL_NO VARCHAR2(150) NOT NULL,
	FINAL_EDU_SE_CD CHAR(3) NOT NULL,
	SAL_TRANS_BANK_CD CHAR(3) NOT NULL,
	SAL_TRANS_ACCNT_NO VARCHAR(20) NOT NULL,
	DIRECT_MANAGER_EMP_NO CHAR(10),
	DEPT_CD CHAR(6) NOT NULL
);

ALTER TABLE SQLD.TB_EMP_TEMP ADD CONSTRAINT PK_TB_EMP_TEMP PRIMARY KEY (EMP_NO);

ALTER TABLE SQLD.TB_EMP_TEMP ADD CONSTRAINT FK_TB_EMP_TEMP_01 FOREIGN KEY (DEPT_CD) REFERENCES SQLD.TB_DEPT_TEMP (DEPT_CD); -- 참조 무결성 제약 조건

----------------------------------
ALTER TABLE SQLD.TB_EMP_TEMP ADD(MARRIED_YN CHAR(1)); -- ADD COLUMN: 칼럼 추가

ALTER TABLE SQLD.TB_EMP_TEMP DROP COLUMN MARRIED_YN; -- DROP COLUMN: 칼럼 삭제

ALTER TABLE SQLD.TB_EMP_TEMP ADD (MARRIED_YN CHAR(1)); -- ADD COLUMN: 칼럼 추가
ALTER TABLE SQLD.TB_EMP_TEMP MODIFY (MARRIED_YN CHAR(1) DEFAULT 'N' NOT NULL NOVALIDATE); -- MODIFY COLUMN: 칼럼 수정, DEFAULT 값 지정
ALTER TABLE SQLD.TB_EMP_TEMP DROP COLUMN MARRIED_YN; -- DROP COLUMN: 칼럼 삭제

CREATE TABLE SQLD.TB_EMP_TEMP_2
AS SELECT * FROM SQLD.TB_EMP_TEMP;

ALTER TABLE SQLD.TB_EMP_TEMP_2
RENAME COLUMN TEL_NO TO PHONE_NO; -- RENAME COLUMN: 칼럼 이름 변경(Oracle 등 일부 DBMS에서만 지원하는 기능)

SELECT * FROM TB_EMP_TEMP_2;

ALTER TABLE SQLD.TB_EMP_TEMP_2
RENAME COLUMN PHONE_NO TO TEL_NO; -- RENAME COLUMN: 칼럼 이름 변경 (PHONE_NO -> TEL_NO)

SELECT * FROM TB_EMP_TEMP_2;

ALTER TABLE SQLD.TB_EMP_TEMP DROP CONSTRAINT FK_TB_EMP_TEMP_01; -- DROP CONSTRAINT: 제약조건 삭제

ALTER TABLE SQLD.TB_EMP_TEMP ADD CONSTRAINT FK_TB_EMP_TEMP_01 FOREIGN KEY (DEPT_CD) REFERENCES SQLD.TB_DEPT_TEMP (DEPT_CD) -- ADD CONSTRAINT: 제약조건 추가

RENAME TB_EMP_TEMP_2 TO TB_EMP_TEMP_3; -- RENAME TABLE: 테이블 명 변경

TRUNCATE TABLE SQLD.TB_EMP_TEMP_3; -- TRUNCATE TABLE: 테이블의 데이터를 비운다. DELETE와 다르게 삭제한 데이터를 ROLLBACK이 불가능하다.

DROP TABLE SQLD.TB_EMP_TEMP_3; -- DROP TABLE: 테이블을 제거한다.
