SELECT MAX(BIRTH_DE)
     , MIN(BIRTH_DE)
     , COUNT(*)
 FROM TB_EMP;




SELECT A.DEPT_CD
     , (SELECT L.DEPT_NM FROM TB_DEPT L WHERE L.DEPT_CD = A.DEPT_CD) AS DEPT_NM
     , MAX(A.BIRTH_DE) AS "가장 늦은 생년월일" 
     , MIN(A.BIRTH_DE) AS "가장 빠른 생년월일" 
     , COUNT(*) AS "직원수"
 FROM TB_EMP A
GROUP BY A.DEPT_CD
ORDER BY A.DEPT_CD ;


SELECT A.DEPT_CD
     , (SELECT L.DEPT_NM 
          FROM TB_DEPT L 
         WHERE L.DEPT_CD = A.DEPT_CD) AS DEPT_NM
     , MAX(A.BIRTH_DE) AS "가장 늦은 생년월일" 
     , MIN(A.BIRTH_DE) AS "가장 빠른 생년월일" 
     , COUNT(*) AS "직원수"
 FROM TB_EMP A
ORDER BY A.DEPT_CD ;

SELECT A.DEPT_CD
     , (SELECT L.DEPT_NM FROM TB_DEPT L WHERE L.DEPT_CD = A.DEPT_CD) AS DEPT_NM
     , MAX(A.BIRTH_DE) AS "가장 늦은 생년월일" 
     , MIN(A.BIRTH_DE) AS "가장 빠른 생년월일" 
     , COUNT(*) AS "직원수"
 FROM TB_EMP A
GROUP BY A.DEPT_CD
HAVING(COUNT(*)) > 1
ORDER BY A.DEPT_CD ;

SELECT 
       A.EMP_NO
     , (SELECT L.EMP_NM FROM TB_EMP L WHERE L.EMP_NO = A.EMP_NO) AS EMP_NM
     , MAX(A.PAY_AMT) AS MAX_PAY_AMT
     , MIN(A.PAY_AMT) AS MIN_PAY_AMT
     , ROUND(AVG(A.PAY_AMT), 2) AS AVG_PAY_AMT          
FROM TB_SAL_HIS A
WHERE A.PAY_DE BETWEEN '20190101' AND '20191231'
GROUP BY A.EMP_NO
HAVING(ROUND(AVG(A.PAY_AMT), 2)) >= 4700000
ORDER BY A.EMP_NO
;

SELECT 
       A.EMP_NO
     , (SELECT L.EMP_NM FROM TB_EMP L WHERE L.EMP_NO = A.EMP_NO) AS EMP_NM
     , SUM(A.PAY_AMT) AS SUM_PAY_AMT          
FROM TB_SAL_HIS A
WHERE A.PAY_DE BETWEEN '20190101' AND '20191231'
HAVING SUM(A.PAY_AMT) > 55000000
GROUP BY A.EMP_NO
ORDER BY SUM_PAY_AMT DESC
;


SELECT 
      SUM(CASE WHEN BIRTH_DE LIKE '195%' THEN 1 ELSE 0 END) AS "1950년대생"
    , SUM(CASE WHEN BIRTH_DE LIKE '196%' THEN 1 ELSE 0 END) AS "1960년대생"
    , SUM(CASE WHEN BIRTH_DE LIKE '197%' THEN 1 ELSE 0 END) AS "1970년대생"
    , SUM(CASE WHEN BIRTH_DE LIKE '198%' THEN 1 ELSE 0 END) AS "1980년대생"
    , SUM(CASE WHEN BIRTH_DE LIKE '199%' THEN 1 ELSE 0 END) AS "1990년대생"
    , COUNT(*) CNT 
 FROM TB_EMP; 
 
 SELECT 
      DEPT_CD
    , (SELECT L.DEPT_NM FROM TB_DEPT L WHERE L.DEPT_CD = A.DEPT_CD) AS DEPT_NM
    , SUM(CASE WHEN A.BIRTH_DE LIKE '195%' THEN 1 ELSE 0 END) AS "1950년대생"
    , SUM(CASE WHEN A.BIRTH_DE LIKE '196%' THEN 1 ELSE 0 END) AS "1960년대생"
    , SUM(CASE WHEN A.BIRTH_DE LIKE '197%' THEN 1 ELSE 0 END) AS "1970년대생"
    , SUM(CASE WHEN A.BIRTH_DE LIKE '198%' THEN 1 ELSE 0 END) AS "1980년대생"
    , SUM(CASE WHEN A.BIRTH_DE LIKE '199%' THEN 1 ELSE 0 END) AS "1990년대생"
    , COUNT(*) CNT 
 FROM TB_EMP A
GROUP BY A.DEPT_CD
ORDER BY A.DEPT_CD; 


SELECT SUM(NUM), AVG(NUM), MAX(NUM), MIN(NUM) AS SUM_NUM
FROM 
(
SELECT NULL AS NUM FROM DUAL
UNION ALL 
SELECT 10 AS NUM FROM DUAL
UNION ALL 
SELECT 20 AS NUM FROM DUAL
UNION ALL 
SELECT 30 AS NUM FROM DUAL
UNION ALL 
SELECT 40 AS NUM FROM DUAL
)
;
 